name: All Contributors

on:
  push:
    branches:
      - main

permissions: read-all

jobs:
  contributors:
    uses: dymexjs/reusable_workflows/.github/workflows/all-contributors.yml@main
