name: Lint PR

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  main:
    uses: dymexjs/reusable_workflows/.github/workflows/lint-pr.yml@main