name: Npm Publish Utils

on:
  release:
    types: [published]

permissions: write-all

jobs:
  publish:
    uses: dymexjs/reusable_workflows/.github/workflows/publish-npm.yml@main
    secrets:
      npm-token: ${{ secrets.NPM_TOKEN }}
