name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: read-all

jobs:
  test:
    uses: dymexjs/reusable_workflows/.github/workflows/run-tests.yml@main
