name: "Update Changelog"

on:
  release:
    types: [released]

jobs:
  update:
    uses: dymexjs/reusable_workflows/.github/workflows/update-changelog.yml@main
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # updated CHANGELOG back to the repository.
      # https://github.blog/changelog/2023-02-02-github-actions-updating-the-default-github_token-permissions-to-read-only/
      contents: write
